# Generated by Django 2.2 on 2019-04-21 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('created_on', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'employee',
                'ordering': ['id'],
            },
        ),
    ]
